### ISSUE TITLE
Discuss per default deployment of the Intel Python distribution

### ISSUE THREAD

**Issue by kathoef** [ExaESM-WP4/JupyterHub-Evaluation-Whitepaper#10]
We could/should discuss the per default deployment of the Intel Python distribution. There was some material provided during the training course "Introduction to the programming and usage of the supercomputer resources at Jülich" (November 2019) [here](https://www.fz-juelich.de/SharedDocs/Downloads/IAS/JSC/EN/slides/supercomputer-ressources-2019-11/15a-tuning_intel.html?nn=1000668) that links [this brief benchmarking blog post](https://www.pugetsystems.com/labs/hpc/Intel-Python-Preview-752/). (It might be very instructive to do some short benchmarks on JUWELS/JURECA hardware?)

Official information might be found [here](https://software.intel.com/en-us/distribution-for-python) with packages being distributed via e.g. an [Anaconda channel](https://software.intel.com/en-us/articles/using-intel-distribution-for-python-with-anaconda) or as [Docker containers](https://software.intel.com/en-us/articles/docker-images-for-intel-python)!

**Comment by willirath** [comment]
If I remember correctly, Natalja from AWI had tested / deployed Python from this channel as well.
