### ISSUE TITLE
Provide reference to available Jupyter@JSC repositories

### ISSUE THREAD

**Issue by kathoef** [ExaESM-WP4/JupyterHub-Evaluation-Whitepaper#12]
There is especially https://github.com/jupyter-jsc, but there are also e.g. https://gitlab.version.fz-juelich.de/jupyter4jsc and https://gitlab.version.fz-juelich.de/jupyterhub-unicore.

**Comment by kthust** [comment]
I asked internally, which one should be provided as reference and get back here when I have feedback.

**Comment by kthust** [comment]
Found this issue and asked again: in the mean time there was some restructuring. All `jupyter-jsc` prefixed repos on https://github.com/FZJ-JSC are related to the Jupyter-JSC Webservice.

**Comment by kathoef** [comment]
Thanks... this will be part of #39, and I already close.
