### ISSUE TITLE
Use Singularity container as Jupyter kernel

### ISSUE THREAD

**Issue by kathoef** [ExaESM-WP4/JupyterHub-Evaluation-Whitepaper#6]
Should work similarly to setting up a conda environment Jupyter kernel. Need to figure out the mappings, though. Useful documentation and starting points might be those:

* https://jupyter-client.readthedocs.io/en/stable/kernels.html (documentation)
* https://github.com/tamera-lanham/ipython-kernel-docker (recent, but extensive)
* https://github.com/clemsonciti/singularity-in-jupyter-notebook (older, but more simple)

**Comment by willirath** [comment]
Done.
